apiVersion: apps/v1
kind: Deployment
metadata:
  name: runcode-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: runcode-worker
  template:
    metadata:
      labels:
        app: runcode-worker
    spec:
      containers:
      - name: runcode-worker
        image: coding-worker:latest
        imagePullPolicy: Never
        env:
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPRING_PROFILES_ACTIVE
          value: "runcodeworker,worker"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 